# =====================================================
# File: k8s/mlflow-service.yaml
# Author: Steven James L00196960
# openMLflow UI on port 5000 standard mlflow Ui
# =====================================================

apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer